development:
  #adapter: mysql
  #encoding: utf8
  #database: misparadas_development
  #username: root
  #host: localhost
  #password:
  adapter: sqlite3
  database: db/development.sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

